BeatBlissApi/urls.py
from django.contrib import admin
from django.urls import path, include
from post.api.router import router_posts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router_posts.urls)),
    path('',include('post.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import *

app_name = 'BeatBlissApi'

urlpatterns = [
    path('converter', converter_page, name='converter-page'),
    path('song-create', song_create, name='song-create'),
    path('album-create', album_create, name='album-create'),
    path('artist-create', artist_create, name='artist-create'),
    path('genre-create', genre_create, name='genre-create'),
 
]

post/models.py
from django.db import models

class SongFile(models.Model):
    songName = models.CharField(max_length=100, default='')
    binary_file = models.BinaryField()
    
    def __str__(self):
        return  str(self.id)

class Artist(models.Model):
    artistName = models.CharField(max_length=100)
    artistImg = models.BinaryField()
    artistDesc = models.TextField()
    
    def __str__(self):
        return self.artistName
    
class Genre(models.Model):
    genreName = models.CharField(max_length=100)
    
    def __str__(self):
        return self.genreName

class Song(models.Model):
    songName = models.CharField(max_length=100)
    songImg = models.BinaryField()
    artistName = models.ForeignKey('Artist', on_delete=models.CASCADE) 
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE)
    year = models.IntegerField()
    mp3_file = models.OneToOneField(SongFile, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.songName
    
class Album(models.Model):
    albumName = models.CharField(max_length=100)
    albumImg = models.BinaryField()
    albumDesc = models.TextField()
    songs = models.ManyToManyField(Song)
    
    def __str__(self):
        return self.albumName
    

class User(models.Model):
    username = models.CharField(max_length=100, blank=True)
    password = models.CharField(max_length=100, blank=True )
    email = models.CharField(max_length=100, blank=True)
    playlists = models.ManyToManyField(Album, blank=True)
    
    def __str__(self):
        return self.username
    

post/api/views.py
from rest_framework import status
from rest_framework.response import Response

from rest_framework.viewsets import ModelViewSet
from post.models import Song, SongFile, Album, Artist, Genre, User
from post.api.serializers import PostSerializer, SongFileSerializer, AlbumSerializer, ArtistSerializer, GenreSerializer, UserSerializer


class PostApiViewSet(ModelViewSet):
    serializer_class = PostSerializer
    queryset = Song.objects.all()

class SongFilesApiViewSet(ModelViewSet):
    serializer_class = SongFileSerializer
    queryset = SongFile.objects.all()

class AlbumApiViewSet(ModelViewSet):
    serializer_class = AlbumSerializer
    queryset = Album.objects.all()

class ArtistApiViewSet(ModelViewSet):
    serializer_class = ArtistSerializer
    queryset = Artist.objects.all()

class GenreApiViewSet(ModelViewSet):
    serializer_class = GenreSerializer
    queryset = Genre.objects.all()

class UserApiViewSet(ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def create(self, request, *args, **kwargs):
        username = request.data.get('username', None)
        email = request.data.get('email', None)
        
        if User.objects.filter(email=email).exists():
            return Response(
                {"error": "Ya existe una cuenta con el mismo correo."},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        if User.objects.filter(username=username).exists():
            return Response(
                {"error": "Ya existe una cuenta con el mismo nombre."},
                status=status.HTTP_400_BAD_REQUEST
            )

        return super().create(request, *args, **kwargs)

post/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from post.models import *
import base64
import gzip
from pydub import AudioSegment

def converter_page(request):
    songs = Song.objects.all()
    albums = Album.objects.all()
    artists = Artist.objects.all()
    genres = Genre.objects.all()
    context = {
        'songs': songs,
        'albums': albums,
        'artists':artists,
        'genres':genres,
    }
    return render(request, 'pages/converterpage.html', context)

def artist_create(request):
    if request.method == 'POST':
        artistName = request.POST.get('artistNameId')
        artistImg = request.FILES['artistImgId'].read()
        artistDesc = request.POST.get('artistDescId')
        
        Artist.objects.create(
            artistName=artistName,
            artistImg=artistImg,
            artistDesc=artistDesc,
        )
         
    return redirect('BeatBlissApi:converter-page')
        
def genre_create(request):
    if request.method == 'POST':
        genreName = request.POST.get('genreNameId')
        allGenres = Genre.objects.all()
        
        for genre in allGenres:
            if genreName == genre.genreName:
                print('Genre already exists')
                return redirect('BeatBlissApi:converter-page')
        
        print('Genre does not exist')
        Genre.objects.create(
            genreName=genreName,
        )
        
    return redirect('BeatBlissApi:converter-page')

def song_create(request):
    if request.method == 'POST':
        songName = request.POST.get('songNameId')
        songImg = request.FILES['songImgId'].read()
        artistName = Artist.objects.get(artistName=request.POST.get('artistId'))
        genre = Genre.objects.get(genreName=request.POST.get('genreId'))
        year = request.POST.get('yeartId')
        mp3_file = SongFile.objects.create(songName=songName,binary_file = request.FILES['mp3FileId'].read())
        
        Song.objects.create(
            songName = songName,
            songImg = songImg,
            artistName = artistName,
            genre = genre,
            year = year,
            mp3_file = mp3_file
        )
          
    return redirect('BeatBlissApi:converter-page')

def album_create(request):
    if request.method == 'POST':
        albumName = request.POST.get('albumSelected')
        if albumName == 'newAlbum':
            albumName = request.POST.get('newAlbumName')
        songIds = request.POST.getlist('selected_songs')
        songs = []
        for songId in songIds:
            songs.append(Song.objects.get(id=songId))
        
        album,created = Album.objects.update_or_create(
            albumName=albumName,
        )
        if not created:
            album.songs.set(songs)
            
        if 'albumImgId' in request.FILES:
            album.albumImg = request.FILES['albumImgId'].read()
        
        if request.POST['albumDescId'] != '':
            album.albumDesc = request.POST['albumDescId']
            
        album.save()
    return redirect('BeatBlissApi:converter-page')

post/templates/pages/converterpage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>converter Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
  </head>
  <body class="container mt-5 bg-black">
    {% comment %}Album Create / Update and Cards{% endcomment %}
    <div class="">
      <form method="POST" enctype="multipart/form-data" action="{% url 'BeatBlissApi:album-create' %}">
        {% csrf_token %}
        <div class="d-flex justify-content-center text-white mb-2">
          <label>Modifica un album existente o selecciona New Album para crear uno:</label>
        </div>
        <div class="d-flex justify-content-center gap-2">
          <input type="text" class="form-control bg-dark text-white" id="newAlbumName" name="newAlbumName" placeholder="Album Name" />
          <input type="file" class="form-control bg-dark text-white" id="albumImgId" name="albumImgId" accept="image/jpeg, image/jpg, image/png" placeholder="Album Img" />
          <input type="text" class="form-control bg-dark text-white" id="albumDescId" name="albumDescId" placeholder="Album Description" />
          <select id="albumSelected" name="albumSelected" class="">
            {% for album in albums %}
              <option value="{{ album.albumName }}">{{ album.albumName }}</option>
            {% endfor %}
            <option value="newAlbum">New Album</option>
          </select>
          <button type="submit" class="btn btn-secondary">Create/Update</button>
        </div>
        {% comment %}Song Cards{% endcomment %}
        <div class="row">
          {% for song in songs %}
            <div class="col-md-4 mt-3">
              <div class="card">
                <div class="card-body bg-dark text-white d-flex justify-content-around">
                  <div>
                    <h5>{{ song.songName }}</h5>
                    <p>{{ song.artistName }}</p>
                  </div>
                  <input type="checkbox" name="selected_songs" value="{{ song.id }}" />
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </form>
    </div>

    {% comment %}Artist Create{% endcomment %}
    <div class="mt-4">
      <div class="d-flex justify-content-center text-white mb-2">
        <label>Añade un artista:</label>
      </div>
      <form method="POST" enctype="multipart/form-data" action="{% url 'BeatBlissApi:artist-create' %}">
        {% csrf_token %}
        <div class="d-flex justify-content-center gap-2">
          <input type="text" class="form-control bg-dark text-white" id="artistNameId" name="artistNameId" placeholder="Artist Name" required />
          <input type="file" class="form-control bg-dark text-white" id="artistImgId" name="artistImgId" accept="image/jpeg, image/jpg, image/png" placeholder="Artist Img" required />
          <input type="text" class="form-control bg-dark text-white" id="artistDescId" name="artistDescId" placeholder="Artist Description" required />
          <button type="submit" class="btn btn-secondary">Create</button>
        </div>
      </form>
    </div>

    {% comment %}Genre Create{% endcomment %}
    <div class="mt-4">
      <div class="d-flex justify-content-center text-white mb-2">
        <label>Añade un genero:</label>
      </div>
      <form method="POST" action="{% url 'BeatBlissApi:genre-create' %}">
        {% csrf_token %}
        <div class="d-flex justify-content-center gap-2">
          <input type="text" class="form-control bg-dark text-white" id="genreNameId" name="genreNameId" placeholder="Genre Name" required />
          <button type="submit" class="btn btn-secondary">Create</button>
        </div>
      </form>
    </div>

    {% comment %}Add Song{% endcomment %}
    <div class="d-flex flex-column align-items-center justify-content-center mt-5 gap-2">
      <form action="{% url 'BeatBlissApi:song-create' %}" method="POST" enctype="multipart/form-data" class="d-flex flex-column gap-2">
        {% csrf_token %}
        <input type="text" class="form-control bg-dark text-white" id="songNameId" name="songNameId" placeholder="Song Name" required />
        <input type="file" class="form-control bg-dark text-white" id="songImgId" name="songImgId" accept="image/jpeg, image/jpg, image/png" placeholder="Song Img" required />
        <select id="artistId" name="artistId" required>
          <option value="" disabled selected>Selecciona un artista</option>
          {% for artist in artists %}
            <option value="{{ artist.artistName }}">{{ artist.artistName }}</option>
          {% endfor %}
        </select>
        <select id="genreId" name="genreId" required>
          <option value="" disabled selected>Selecciona un genero</option>
          {% for genre in genres %}
            <option value="{{ genre.genreName }}">{{ genre.genreName }}</option>
          {% endfor %}
        </select>
        <input type="text" class="form-control bg-dark text-white" id="yeartId" name="yeartId" placeholder="Year" required />
        <input type="file" class="form-control bg-dark text-white" id="mp3FileId" name="mp3FileId" accept=".mp3" placeholder="Mp3File" required />
        <button type="submit" class="btn btn-primary">Add Song</button>
      </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>